image: kitware/vtk-for-ci:v9.1.0
stages:
  - build
  - test

build-module:
  stage: build
  script:
    - mkdir -p build
    - cd build
    - cmake -DVTK_DIR=/vtk/build/ -DBUILD_TESTING=ON ..
    - cmake --build . --config Release --parallel 2
  tags:
    - docker
    - linux
    - shared
  artifacts:
    expire_in: 1h
    when: always
    paths:
      - build/

test-module:
  stage: test
  script:
    - cd build
    - ctest -C Release -j 2 --output-on-failure || ctest -C Release -j 1 --rerun-failed -VV
  tags:
    - docker
    - linux
    - shared
  dependencies:
    - build-module
  needs:
    - build-module
