stages:
  - build
  - test

.build-module:
  stage: build
  script:
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_PREFIX_PATH=/opt/vtk/install/ -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Release ..
    - cmake --build . --parallel 2
  tags:
    - docker
    - linux
    - vtk
  artifacts:
    expire_in: 1h
    when: always
    paths:
      - build/

.test-module:
  stage: test
  script:
    - cd build
    - export LD_LIBRARY_PATH=/opt/vtk/install/lib/:$LD_LIBRARY_PATH
    - xvfb-run ctest -j 2 --output-on-failure || xvfb-run ctest -j 1 --rerun-failed -VV
  tags:
    - docker
    - linux
    - vtk

.latest:
  image: kitware/vtk-for-ci:latest
  rules:
    - if: $DISABLE_LATEST == "True"
      when: never
    - when: on_success

.v922:
  image: kitware/vtk-for-ci:v9.2.2
  rules:
    - if: $DISABLE_V922 == "True"
      when: never
    - when: on_success

.v910:
  image: kitware/vtk-for-ci:v9.1.0
  rules:
    - if: $DISABLE_V910 == "True"
      when: never
    - when: on_success

.v903:
  image: kitware/vtk-for-ci:v9.0.3
  rules:
    - if: $DISABLE_V903 == "True"
      when: never
    - when: on_success

build-module-latest:
  extends:
    - .build-module
    - .latest

test-module-latest:
  extends:
    - .test-module
    - .latest
  dependencies:
    - build-module-latest
  needs:
    - build-module-latest

build-module-v9.2.2:
  extends:
    - .build-module
    - .v922

test-module-v9.2.2:
  extends:
    - .test-module
    - .v922
  dependencies:
    - build-module-v9.2.2
  needs:
    - build-module-v9.2.2

build-module-v9.1.0:
  extends:
    - .build-module
    - .v910

test-module-v9.1.0:
  extends:
    - .test-module
    - .v910
  dependencies:
    - build-module-v9.1.0
  needs:
    - build-module-v9.1.0

build-module-v9.0.3:
  extends:
    - .build-module
    - .v903

test-module-v9.0.3:
  extends:
    - .test-module
    - .v903
  dependencies:
    - build-module-v9.0.3
  needs:
    - build-module-v9.0.3
