workflow:
   rules:
     - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == "master"
       when: always
     - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == "main"
       when: always
     - if: $CI_MERGE_REQUEST_ID
       when: always
     - when: never

stages:
  - build
  - test

.build-module:
  stage: build
  script:
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_PREFIX_PATH=/opt/vtk/install/ -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Release ..
    - cmake --build . --parallel 2
  tags:
    - docker
    - linux-x86_64
    - vtk
  artifacts:
    expire_in: 1h
    when: always
    paths:
      - build/

.test-module:
  stage: test
  script:
    - cd build
    - export LD_LIBRARY_PATH=/opt/vtk/install/lib/:$LD_LIBRARY_PATH
    - xvfb-run ctest -j 2 --output-on-failure || xvfb-run ctest -j 1 --rerun-failed -VV
  tags:
    - docker
    - linux-x86_64
    - vtk

.latest:
  image: kitware/vtk-for-ci:latest
  variables:
    VTK_VERSION: "latest"
  rules:
    - if: $DISABLE_LATEST == "True"
      when: never
    - when: on_success

.v9_2:
  image: kitware/vtk-for-ci:v9.2.6
  variables:
    VTK_VERSION: "9.2.6"
  rules:
    - if: $DISABLE_9_2 == "True"
      when: never
    - when: on_success

.v9_1:
  image: kitware/vtk-for-ci:v9.1.0
  variables:
    VTK_VERSION: "9.1.0"
  rules:
    - if: $DISABLE_9_1 == "True"
      when: never
    - when: on_success

.v9_0:
  image: kitware/vtk-for-ci:v9.0.3
  variables:
    VTK_VERSION: "9.0.3"
  rules:
    - if: $DISABLE_9_0 == "True"
      when: never
    - when: on_success

build-module-latest:
  extends:
    - .build-module
    - .latest

test-module-latest:
  extends:
    - .test-module
    - .latest
  dependencies:
    - build-module-latest
  needs:
    - build-module-latest

build-module-v9.2.6:
  extends:
    - .build-module
    - .v9_2

test-module-v9.2.6:
  extends:
    - .test-module
    - .v9_2
  dependencies:
    - build-module-v9.2.6
  needs:
    - build-module-v9.2.6

build-module-v9.1.0:
  extends:
    - .build-module
    - .v9_1

test-module-v9.1.0:
  extends:
    - .test-module
    - .v9_1
  dependencies:
    - build-module-v9.1.0
  needs:
    - build-module-v9.1.0

build-module-v9.0.3:
  extends:
    - .build-module
    - .v9_0

test-module-v9.0.3:
  extends:
    - .test-module
    - .v9_0
  dependencies:
    - build-module-v9.0.3
  needs:
    - build-module-v9.0.3
