image: kitware/vtk-for-ci:v9.1.0
stages:
  - build
  - test

.build-module:
  stage: build
  script:
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_PREFIX_PATH=/opt/vtk/install/ -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Release ..
    - cmake --build . --parallel 2
  tags:
    - docker
    - linux
    - vtk
  artifacts:
    expire_in: 1h
    when: always
    paths:
      - build/

.test-module:
  stage: test
  script:
    - cd build
    - export LD_LIBRARY_PATH=/opt/vtk/install/lib/:$LD_LIBRARY_PATH
    - xvfb-run ctest -j 2 --output-on-failure || xvfb-run ctest -j 1 --rerun-failed -VV
  tags:
    - docker
    - linux
    - vtk

build-module-latest:
  extends:
    - .build-module
  image: kitware/vtk-for-ci:latest

test-module-latest:
  extends:
    - .test-module
  image: kitware/vtk-for-ci:latest
  dependencies:
    - build-module-latest
  needs:
    - build-module-latest

build-module-v9.1.0:
  extends:
    - .build-module
  image: kitware/vtk-for-ci:v9.1.0

test-module-v9.1.0:
  extends:
    - .test-module
  image: kitware/vtk-for-ci:v9.1.0
  dependencies:
    - build-module-v9.1.0
  needs:
    - build-module-v9.1.0

build-module-v9.0.3:
  extends:
    - .build-module
  image: kitware/vtk-for-ci:v9.0.3

test-module-v9.0.3:
  extends:
    - .test-module
  image: kitware/vtk-for-ci:v9.0.3
  dependencies:
    - build-module-v9.0.3
  needs:
    - build-module-v9.0.3
