workflow:
   rules:
     - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == "master"
       when: always
     - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == "main"
       when: always
     - if: $CI_MERGE_REQUEST_ID
       when: always
     - when: never

stages:
  - build
  - test

include:
  - local: .gitlab/common.yml
  - local: .gitlab/latest.yml
  - local: .gitlab/9.4.yml
  - local: .gitlab/9.3.yml
  - local: .gitlab/9.2.yml
  - local: .gitlab/9.1.yml
  - local: .gitlab/9.0.yml
