image: kitware/vtk-for-ci:v9.1.0
stages:
  - build
  - test

build-module:
  stage: build
  script:
    - mkdir -p build
    - cd build
    - cmake -DVTK_DIR=/vtk/install/lib/cmake/vtk-9.1/ -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Release ..
    - cmake --build . --parallel 2
  tags:
    - docker
    - linux
    - vtk
  artifacts:
    expire_in: 1h
    when: always
    paths:
      - build/

test-module:
  stage: test
  script:
    - cd build
    - export LD_LIBRARY_PATH=/vtk/install/lib/:$LD_LIBRARY_PATH
    - xvfb-run ctest -j 2 --output-on-failure || ctest -j 1 --rerun-failed -VV
  tags:
    - docker
    - linux
    - vtk
  dependencies:
    - build-module
  needs:
    - build-module
